=== cte-zl-ifrn/ava__integrador/src/middleware/diario.schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/Welcome1",
    "definitions": {
        "Welcome1": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "campus": {
                    "$ref": "#/definitions/Campus"
                },
                "curso": {
                    "$ref": "#/definitions/Curso"
                },
                "turma": {
                    "$ref": "#/definitions/Turma"
                },
                "componente": {
                    "$ref": "#/definitions/Componente"
                },
                "diario": {
                    "$ref": "#/definitions/Diario"
                },
                "polo": {
                    "type": "null"
                },
                "professores": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Professor"
                    }
                },
                "alunos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Aluno"
                    }
                }
            },
            "required": [
                "alunos",
                "campus",
                "componente",
                "curso",
                "diario",
                "polo",
                "professores",
                "turma"
            ],
            "title": "Welcome1"
        },
        "Aluno": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "integer"
                },
                "matricula": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "email_secundario": {
                    "type": "string"
                },
                "situacao": {
                    "type": "string"
                },
                "polo": {
                    "type": "null"
                }
            },
            "required": [
                "email",
                "email_secundario",
                "id",
                "matricula",
                "nome",
                "polo",
                "situacao"
            ],
            "title": "Aluno"
        },
        "Campus": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "integer"
                },
                "descricao": {
                    "type": "string"
                },
                "sigla": {
                    "type": "string"
                }
            },
            "required": [
                "descricao",
                "id",
                "sigla"
            ],
            "title": "Campus"
        },
        "Componente": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "integer"
                },
                "sigla": {
                    "type": "string"
                },
                "descricao": {
                    "type": "string"
                },
                "descricao_historico": {
                    "type": "string"
                },
                "periodo": {
                    "type": "null"
                },
                "tipo": {
                    "type": "integer"
                },
                "optativo": {
                    "type": "boolean"
                },
                "qtd_avaliacoes": {
                    "type": "integer"
                }
            },
            "required": [
                "descricao",
                "descricao_historico",
                "id",
                "optativo",
                "periodo",
                "qtd_avaliacoes",
                "sigla",
                "tipo"
            ],
            "title": "Componente"
        },
        "Curso": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "integer"
                },
                "codigo": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "descricao": {
                    "type": "string"
                }
            },
            "required": [
                "codigo",
                "descricao",
                "id",
                "nome"
            ],
            "title": "Curso"
        },
        "Diario": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "integer"
                },
                "situacao": {
                    "type": "string"
                },
                "descricao": {
                    "type": "string"
                },
                "descricao_historico": {
                    "type": "string"
                },
                "sigla": {
                    "type": "string"
                }
            },
            "required": [
                "descricao",
                "descricao_historico",
                "id",
                "sigla",
                "situacao"
            ],
            "title": "Diario"
        },
        "Professor": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "integer"
                },
                "login": {
                    "type": "string",
                    "format": "integer"
                },
                "nome": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "email_secundario": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "tipo": {
                    "type": "string"
                }
            },
            "required": [
                "email",
                "email_secundario",
                "id",
                "login",
                "nome",
                "status",
                "tipo"
            ],
            "title": "Professor"
        },
        "Turma": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "integer"
                },
                "codigo": {
                    "type": "string"
                }
            },
            "required": [
                "codigo",
                "id"
            ],
            "title": "Turma"
        }
    }
}

=== cte-zl-ifrn/ava__integrador/src/src2/painel/examples/request.json
{
    "campus": {
        "id": 1,
        "descricao": "NOME COMPLETO DO CAMPUS",
        "sigla": "NCC"
    },
    "curso": {
        "id": 1,
        "codigo": "00001",
        "nome": "Tecnologia em Redes de Computadores",
        "descricao": "Tecnologia em Redes de Computadores - Nome Completo do Campus"
    },
    "turma": {
        "id": 1,
        "codigo": "20221.6.00001.1E"
    },
    "diario": {
        "id": 1,
        "situacao": "Aberto",
        "descricao": "Bancos de Dados",
        "descricao_historico": "Bancos de Dados",
        "sigla": "TEC.0001"
    },
    "professores": [
        {
            "id": 1,
            "login": "1234567",
            "nome": "Nome completo de um professor principal",
            "email": "nome.sobrenome@ifrn.edu.br",
            "email_secundario": "nome.sobrenome@gmail.com",
            "status": "ativo",
            "tipo": "Principal"
        }
    ],
    "alunos": [
        {
            "id": 1,
            "matricula": "20183000010001",
            "nome": "Nome completo do aluno",
            "email": "nome.compelto@academico.ifrn.edu.br",
            "email_secundario": "nome.completo@hotmail.com",
            "situacao": "ativo",
            "polo": null
        }
    ],
    "polo": null,
    "componente": {
        "id": 1,
        "sigla": "TEC.0001",
        "descricao": "Bancos de Dados",
        "descricao_historico": "Bancos de Dados",
        "periodo": null,
        "tipo": 1,
        "optativo": false,
        "qtd_avaliacoes": 2
    }
}
